name: desafio

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Build
            run: echo Building the app
  
    prd:
       runs-on: ubuntu-latest
       environment:
          name: prd
          url: 200.203.76.242:/home/anakin/desafio
       needs: build
       steps:
         - name: 🚚 Get latest code
           uses: actions/checkout@v2
           
         - name: 📂 Sync files
           uses: SamKirkland/FTP-Deploy-Action@4.0.0
           with:
            server: 192.168.100.222
            username: anakin
            password: Eunaoseiasenha22
            server-dir: /home/anakin/desafio/
         


#    steps:
#    - uses: actions/checkout@v3
#   - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
####        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml#
#
    