name: desafio

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      services:
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
          - name: Build
            run: echo Building the app
  
    prd:
       runs-on: ubuntu-latest
       environment:
          name: prd
          url: 200.203.76.242:/home/anakin/desafio
      
       needs: build
       steps:
         - name: Repo Checkout
           uses: actions/checkout@v1
         - name: 📂 Sync files
           uses: SamKirkland/FTP-Deploy-Action@4.0.0
           with:
            server: 192.168.100.222
            username: anakin
            password: Eunaoseiasenha22
            server-dir: /home/anakin/desafio/
          
         - name: Prd
           uses: easingthemes/ssh-deploy@main
           with:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "public/"
            REMOTE_HOST: ${{vars.REMOTE_HOST}}
            REMOTE_USER: ${{vars.REMOTE_USER}}
            REMOTE_PORT: ${{vars.REMOTE_PORT}}


#    steps:
#    - uses: actions/checkout@v3
#   - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
####        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml#
#
    