name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    build:

    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Building the app
  
      deploy-prd:
        runs-on: ubuntu-latest
        environmet:
          name: prd
          url: 200.203.76.242/home/anakin/desafio
        needs: build
        steps:
          - name: Repo Checkout
            uses: action/checkout@v1
          - name: Prd
            uses: easingthemes/ssh-deploy@main
            with:
              SSH_PRIVATE_KEY: ${{SERVER_SSH_KEY}}
              ARGS: "-rlgoDzvc --delete"
              SOURCE: "public/"
              REMOTE_HOST: ${{vars.REMOTE_HOST}}
              REMOTE_USER: ${{vars.REMOTE_USER}}
              REMOTE_PORT: ${{vars.REMOTE_PORT}}
#              TARGET:  ${{vars.TARGET}}



#
#    steps:
#    - uses: actions/checkout@v3
#   - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
####        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml#

      



